# Bindings
bind '"\C-o":"lfcd\C-m"'
bind '"\C-t":"tmux new -s h@ck -n main\C-m"'

# Very much possible tab completion
bind 'set show-all-if-ambiguous on'
bind 'TAB:menu-complete'

shopt -s histappend
shopt -s checkwinsize
shopt -s autocd
shopt -s expand_aliases 

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# Bash History
HISTCONTROL=ignoreboth
HISTSIZE=100
HISTFILESIZE=200
HISTFILE="${XDG_CACHE_HOME:-$HOME/.cache}/bash/history"

# Load aliases and shortcuts if existent.
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/bash/aliasrc" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/bash/aliasrc"

# enable programmable completion features 
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# the beautiful bash prompt
PS1="\[\033[1;32m\]\w $ \[\033[00m\]" # Setting PS1 to show full path
export PROMPT_DIRTRIM=4 # Trimming path to 4 directories

# lfcd script
LFCD="/home/mthich/.local/bin/lfcd"
if [ -f "$LFCD" ]; then
    source "$LFCD"
fi
